spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://211.37.173.118:3306/iomt_portal
    username: chnops1
    password: chnops1234

## Mybatis Setting ##
mybatis:
  type-aliases-package: com.code.test
  mapper-locations: mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: fdjkasljfkdlasjkfljdkajfkdlasjkfljkasljfkldjsakljfkdlasjfklsljfkldasjklfjdkasljfkldasjkl
